default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: "1234"
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *default
  database: y_com_development

test:
  <<: *default
  database: y_com_test

production:
  <<: *default
  database: y_com_production
  username: y_com
  password: <%= ENV["Y_COM_DATABASE_PASSWORD"] %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>

cable:
  <<: *default
  database: y_com_production
  username: y_com
  password: <%= ENV["Y_COM_DATABASE_PASSWORD"] %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  migrations_paths: db/migrate

queue:
  <<: *default
  database: y_com_production
  username: y_com
  password: <%= ENV["Y_COM_DATABASE_PASSWORD"] %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  migrations_paths: db/migrate

cache:
  <<: *default
  database: y_com_production
  username: y_com
  password: <%= ENV["Y_COM_DATABASE_PASSWORD"] %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  migrations_paths: db/migrate